touchscreen: goodix_driver_gt9886: Fix compilation when built as module
When `CONFIG_TOUCHSCREEN_GOODIX_GTX8_UPDATE` is set to build as a module,
the following errors can be seen:
../drivers/input/touchscreen/goodix_driver_gt9886/goodix_gtx8_update.c:1448:5: error: redefinition of 'goodix_do_fw_update'
 1448 | int goodix_do_fw_update(int mode)
      |     ^
../drivers/input/touchscreen/goodix_driver_gt9886/goodix_ts_core.h:858:19: note: previous definition is here
  858 | static inline int goodix_do_fw_update(int mode)
      |                   ^
1 error generated.

Fix this by using `IS_ENABLED` macro instead of standard `ifdef`

Change-Id: Ida9df47efb20f68fae6e0dcd71da49bc846a7539
Signed-off-by: UtsavBalar1231 <utsavbalar1231@gmail.com>